### PR TITLE
Use Searchisko v2 on "Upstream Projects" pages on jboss.org.

### PR DESCRIPTION
**Pull request by lukas-vlcek**
See ORG-2501

### CODE REVIEW

**Comment by paulrobinson** [comment]
Sorry I missed this before. Take a look at: http://www-stg.jboss.org/pr/932/build/2184/projects/

**Comment by lukas-vlcek** [comment]
OK, we need to change the query for featured projects to <http://_dcp_server_/v2/rest/search/suggest_project_name_ngram_more_fields?sort=sys_title&project=wildfly&project=drools&project=jbosstools>

**Comment by lukas-vlcek** [comment]
@paulrobinson I think it works better now.

**Comment by paulrobinson** [comment]
Thanks @lukas-vlcek, looks good now.

**Pull request merged**
