### PR TITLE
First attempt at fixing DEVELOPER-491

### PR DESCRIPTION
**Pull request by LightGuard**
View only, don't merge yet.

This works on the quickstarts currently. It seems we have been handling
contributors different ways in different places.

### CODE REVIEW

**Comment by paulrobinson** [comment]
Let me know when this is ready for review.

**Comment by LightGuard** [comment]
Minus the ones we create via js, this is ready

**Comment by paulrobinson** [comment]
See: http://www-stg.jboss.org/pr/753/build/1648/developer-materials/#!

Notice that Vineet and Pete both have broken G+ url of https://google.com/undefined?rel=author

**Comment by paulrobinson** [comment]
Also the profile image for Pete looks stretched: http://www-stg.jboss.org/pr/753/build/1648/ticket-monster/adminhtml5/

**Comment by paulrobinson** [comment]
FYI the G+ links on the quickstart detail pages work. It looks like it's a bug in just the JS version.

**Comment by paulrobinson** [comment]
I'm going to close this for now as it looks like there is quite a bit of work remaining. Given current work, this is not going to be a priority to address for quite a while. Lets keep the branches around though, so as we can come back to it. We might need to use this code as a basis for another site we are working on at the moment.

**Pull request closed without merging**
