### PR TITLE
DEVELOPER-1423 - Added ability to reference canonical owner

### PR DESCRIPTION
**Pull request by Dantheman720**
Still need to add a way to customize the hrefs since not all of them will follow the convention that I added.  I am thinking about adding a field where you can customize the url where it will overwrite the default for each quickstart (just in case).

### CODE REVIEW

**Comment by paulrobinson** [comment]
Does the yaml file need to be so complex? I was thinking something like this:

     - !ruby/regexp /^.*\/quickstarts\/.*/
     - !ruby/regexp /^.*\/demos\/.*/
     ...

I appreciate that this doesn't work in the cases where the URL pattern is not identical. However, do we have any such cases?

**Comment by Dantheman720** [comment]
Probably not.  That was the way I originally had it :).  The only reason I switched it is in case we wanted to reduce complexity do that we are not iterating over everything (e.g. Videos wouldn't iterate over the quickstarts collection and whatnot...).  It's probably totally unnecessary.  Your suggestion will definitely work.

**Comment by paulrobinson** [comment]
This seems to be working. Can you update the PR to include all resource pages? i.e quickstarts, demos, videos. etc.

**Comment by paulrobinson** [comment]
You're still missing some of the developer materials. In particular, /ticket-monster. /boms, /archetypes.

**Comment by paulrobinson** [comment]
I'll add them in another PR

**Pull request merged**
