### PR TITLE
DEVELOPER-1232 Added the Github token value to secrets.yaml.gpg to be us...

### PR DESCRIPTION
**Pull request by paulrobinson**
...ed in referencing Github API

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
This still doesn't seem to be working. I'm pretty sure it's using this code now: https://github.com/Dantheman720/aweplug/commit/a699f1deba6ad327366a9c2fc28a31e38d5f3009

@Dantheman720 did you see this code working on your laptop?

**Comment by Dantheman720** [comment]
@paulrobinson It is definitely using the header; however, there are 27 requests that don't use the header or the token according to the CI faraday.log

**Comment by Dantheman720** [comment]
@paulrobinson Other than that, I could see the x-ratelimit-limit: variable set to 5000 for most of the api.github.com calls.

**Pull request closed without merging**
