### PR TITLE
Developer 3236

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@Dantheman720 there seems to be an error when building the homepage. Can you take a look? Although I'm not sure how your change would cause that.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@Dantheman720 the homepage issue was caused by an error in the Events spreadsheet which I have now fixed. Retesting to see if it works now.

**Comment by Dantheman720** [comment]
@paulrobinson @LightGuard - Can this be merged?

**Pull request merged**
