### PR TITLE
Adding new AeroGear Docker images

### PR DESCRIPTION
**Pull request by matzew**
* updated the AeroGear project des.
* putting in the new Docker images for AeroGear (UnifiedPush Server (WildFly based) and SimplePush (Netty based)

### CODE REVIEW

**Comment by matzew** [comment]
@abstractj mind to do a quick review here as well ?

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
This looks good: http://www-stg.jboss.org/pr/795/build/1704/docker/

Happy for me to merge?

**Comment by abstractj** [comment]
@paulrobinson go ahead

**Pull request merged**
