### PR TITLE
Artificer Docker image

### PR DESCRIPTION
**Pull request by brmeyer**
Docker image PR: https://github.com/jboss-dockerfiles/artificer/pull/2

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by brmeyer** [comment]
Looks like this is failing for reasons unrelated to the PR: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/www.jboss.org-pull-player-executor/2103/console

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
Take a look at: http://www-stg.jboss.org/pr/903/build/2104/docker/

The links don't seem to be ready yet. Let me know when they are and i'll push it live.

**Comment by brmeyer** [comment]
@paulrobinson, Artificer is now included.  Merge?  Thanks!

**Pull request merged**
