### PR TITLE
DEVELOPER-1210 Ability to add URLs to collateral for each connector

### PR DESCRIPTION
**Pull request by Dantheman720**
For testing at this point.  Let me know how this should be changed.  I updated the partial to display the links and the js hides if it is an empty string.

### CODE REVIEW

**Comment by paulrobinson** [comment]
The vertical spacing between links needs some work. They should be closer together.

**Comment by paulrobinson** [comment]
We are also waiting on approval from Sameer.

**Comment by Dantheman720** [comment]
I updated the css.  It's kind of hacked, but I couldn't get the line spacing to work otherwise.

**Comment by paulrobinson** [comment]
I've removed the sample data from the connectors spreadsheet. This can be merged after 6hrs when the cache is flushed.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
