### PR TITLE
DEVELOPER-3207 set current_version =...

### PR DESCRIPTION
**Pull request by nickboldt**
DEVELOPER-3207 set current_version = 10.0.0.GA ... does this still need to happen\? Is this how the Resources page decides which doc to show\?

### CODE REVIEW

**Comment by paulrobinson** [comment]
Yes, this is needed for the code that infers the URLs of the docs. Unfortunately, for this release the docs are not at a predictable location. See: http://www-stg.jboss.org/pr/1039/build/2357/products/devstudio/resources/

They seem to be articles now. E.g: https://access.redhat.com/articles/2358611. Therefore the locations must be hard-coded in the product.yml file :-(. I can provide examples if you don't know how to do that.

**Comment by nickboldt** [comment]
Please give me an example.

Also, I note that the devstudio 10.0 docs are here:

https://access.redhat.com/documentation/en/red-hat-jboss-developer-studio/

So could we just link people to that?

**Comment by paulrobinson** [comment]
Here's an example: https://github.com/jboss-developer/www.jboss.org/blob/master/products/fuse/_common/product.yml#L30-L39

If one of the formats is unavailable, just leave it off.

We can't just link to the docs page as it reduces the UX on the site. We want to list the developer focused docs on the JBD site and keep people on-site as much as possible.

FYI: The docs team are making a REST API so that we can automatically populate this page like we now do for downloads.

**Comment by nickboldt** [comment]
PR updated to add doc links, as done in https://github.com/redhat-developer/developers.redhat.com/pull/1204

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
