### PR TITLE
DEVELOPER-777 Updated picketlink quickstarts

### PR DESCRIPTION
**Pull request by Dantheman720**
Updated Picketlink quickstarts to the most recent version

### CODE REVIEW

**Comment by paulrobinson** [comment]
This isn't DEVELOPER-777. Can you fix the commit and PR name?

**Comment by Dantheman720** [comment]
I will change this to JDF-777 and resubmit

**Comment by paulrobinson** [comment]
Thanks Dan. Can this be closed now? I see there's a replacement PR.

**Comment by Dantheman720** [comment]
This was opened in error

**Pull request closed without merging**
