### PR TITLE
DEVELOPER-984 (support multiple target products)

### PR DESCRIPTION
**Pull request by LightGuard**
Videos now support multiple target products

### CODE REVIEW

**Comment by LightGuard** [comment]
Merge this one last, it has the latest aweplug.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
Is this replaced by https://github.com/jboss-developer/www.jboss.org/pull/751?

**Comment by LightGuard** [comment]
Yes

On Tuesday, January 27, 2015, Paul Robinson <notifications@github.com>
wrote:

> Is this replaced by #751
> <https://github.com/jboss-developer/www.jboss.org/pull/751>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/741#issuecomment-71645044>
> .
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Pull request closed without merging**
