### PR TITLE
Updating ruby and also dependencies

### PR DESCRIPTION
**Pull request by LightGuard**
This updates our version of ruby to the latest version, and also updates many
of the dependencies we're using. The build will probably die due to not having
the version of ruby installed we need.

### CODE REVIEW

**Comment by LightGuard** [comment]
Figure out how to get blinkr included / excluded for the correct builds.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
It passed, looks like we're good to merge this then. https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/www.jboss.org-pull-player-executor/1664/

**Comment by paulrobinson** [comment]
I forgot to check that this didn't break Blinkr. Looks like it did, so I need to revert it.

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/www.jboss.org-pull-player-blinkr/1002/console

**Comment by paulrobinson** [comment]
Actually, it looks like I spoke too soon, I saw 'NoMethodError' and jumped to the wrong conclusion. It actually looks like it could be an intermittent failure. Re-testing...

**Comment by paulrobinson** [comment]
This also seemed to break the featured connectors on http://www-stg.jboss.org/pr/762/build/1664/products/fuse/connectors/. 

In the console there is this error: "Uncaught SyntaxError: Unexpected token c".

**Pull request merged**
