### PR TITLE
DEVELOPER-2607 - Updated apache logo

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
http://www-stg.jboss.org/pr/1028/build/2343/products/webserver/overview/ - Review the icon on this page

**Comment by paulrobinson** [comment]
@wesbos can you review this please?

**Comment by wesbos** [comment]
@Dantheman720 What did you use to generate the icon font? Did the rest of the icons come along?

**Comment by Dantheman720** [comment]
@wesbos I used https://icomoon.io/ to generate the fonts.  I loaded in the previous .svg file that contained the font grid and switched out the apache logo.  I tried to use font forge, but was struggling to get it to work.

**Comment by wesbos** [comment]
Does Icomoon use font forge behind the scenes? I just want to make sure none of the other icons got goofed up by changing line heights or anything.

**Comment by Dantheman720** [comment]
They don't explicitly state whether or not they use it.  It's probably safer to assume that they don't.

**Comment by wesbos** [comment]
Okay - well it looks like the output is very simiar - you can check the
rest of the places that we have the icons and you don't see anything that
is out of place this is good to merge.

*Wes Bos *
*━━━━━━━*
wesbos.com
Skype: wes.bos
Phone: 416 833 3641
Twitter: @wesbos <http://twitter.com/wesbos>

**Comment by Dantheman720** [comment]
The other product that pulls from it is devstudio, and everything looked alright there as well.

**Comment by wesbos** [comment]
:+1:

**Comment by Dantheman720** [comment]
Thank you sir! :)

**Pull request merged**
