### PR TITLE
DO NOT MERGE Version bumping of blinkr and awestruct

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
Do you still need this? I see it's marked as "DO NOT MERGE"

**Comment by LightGuard** [comment]
Um, probably not.

On Wed, Sep 2, 2015 at 3:57 AM, Paul Robinson <notifications@github.com>
wrote:

> Do you still need this? I see it's marked as "DO NOT MERGE"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/923#issuecomment-137009717>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Pull request closed without merging**
