### PR TITLE
Adding Hawkular Docker image to the list

### PR DESCRIPTION
**Pull request by theute**
Docker image needs to be added first in:
https://registry.hub.docker.com/repos/jboss/

I didn't know how to build to verify so hopefully it will look good...

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
Take a look at: http://www-stg.jboss.org/pr/902/build/2101/docker/

I think we should wait until the links are active before merging.

**Comment by theute** [comment]
+1 it's in @goldmann 's hands now :)
Marek, any ETA to publish the Hawkular docker container ?

**Comment by goldmann** [comment]
s/container/image :)

@theute I added a question to the PR you opened: https://github.com/jboss-dockerfiles/hawkular/pull/1

**Comment by theute** [comment]
@paulrobinson the links work, the docker image works.
:+1:

**Pull request merged**
