### PR TITLE
DEVELOPER-1270 Added BPMSuite and BRMS changes under the Business Resource Management section

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Can you add the banner changes to this PR too.

**Comment by Dantheman720** [comment]
I just rebased this so we should be good to go here

**Comment by paulrobinson** [comment]
Did you see my comment above? The banners are missing.

**Comment by Dantheman720** [comment]
@paulrobinson I think I am misunderstanding.  Which banners are you referring to?  I see the DevNation banners and spotlight

**Comment by paulrobinson** [comment]
See my email with subject: "BPM Suite and BRMS 6.1 Launch".

In particular, this issue needs resolving in this PR too: https://issues.jboss.org/browse/DEVELOPER-1271

**Comment by Dantheman720** [comment]
Ah, good deal.

**Comment by Dantheman720** [comment]
@paulrobinson I merged DEVELOPER-1271 with this one to add both the banners and the content changes to this PR

**Comment by Dantheman720** [comment]
@paulrobinson Does this still require changes?  If so, I can go ahead and make those.

**Comment by paulrobinson** [comment]
It's waiting for the product release, so that we can add the new downloads. Expect to be notified early next week. I'll be sending out an email to you and Pete to coordinate the changes, as I'll be away when the release is expected.

**Comment by paulrobinson** [comment]
Looks like you need a rebase too.

**Pull request closed without merging**
