### PR TITLE
DEVELOPER-1187 Red Hat events is now displaying the shadowman logo

### PR DESCRIPTION
**Pull request by Dantheman720**
I kind of hacked the css together to make the shadowman appear closer to "RED HAT EVENTS".  It seems to scale okay when resizing the screen.

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks fine.

**Comment by Dantheman720** [comment]
Can this be merged?

**Comment by paulrobinson** [comment]
Almost right, see my comments on the JIRA issue.

**Comment by paulrobinson** [comment]
Can you add a bit more padding between the "RED HAT EVENT" text and the green button. Take a look at the mockup in the issue.

**Comment by Dantheman720** [comment]
Will do.

**Pull request merged**
