### PR TITLE
DEVELOPER-1319 Create GIDS Microsite

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
I think you'll need to process images/gids/gids_collage.jpg through https://kraken.io/. James should be able to provide the details.

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
