### PR TITLE
Developer-1353 Downloads

### PR DESCRIPTION
**Pull request by Dantheman720**
The names for AMQ may need to be changed around.  I didn't know exactly what to name each of the items so this will need review.

### CODE REVIEW

**Comment by paulrobinson** [comment]
Why are the docs pages removed?

**Comment by Dantheman720** [comment]
@paulrobinson I commented them out because they were producing broken links.  I can add them back in.

**Comment by paulrobinson** [comment]
I've added them back-in in another PR. Can you add them back in for your RHD PR please.

**Comment by Dantheman720** [comment]
Will do.

**Pull request merged**
