### PR TITLE
Master

### PR DESCRIPTION
**Pull request by eschabell**
Fix to get buzz working again, removed broken tag.

### CODE REVIEW

**Comment by LightGuard** [comment]
This fixes it by removing all the buzz? Not quite sure how this is a fix, wouldn't you want the buzz on the BPM page?

**Comment by eschabell** [comment]
Just looking at BRMS product page, not using buzz_tag and it works fine... this one is currently not working... so adding tag back but now with different format. 

I have to submit each try, can't test locally. :(

**Comment by LightGuard** [comment]
No problems :)

On Tue, Oct 20, 2015 at 2:24 PM, Eric D. Schabell <notifications@github.com>
wrote:

> Just looking at BRMS product page, not using buzz_tag and it works fine...
> this one is currently not working... so adding tag back but now with
> different format.
>
> I have to submit each try, can't test locally. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/981#issuecomment-149549328>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by eschabell** [comment]
No joy and no buzz listed on bpm suite page still....

**Comment by paulrobinson** [comment]
This is how we do it on Red Hat Developers: https://github.com/jboss-developer/www.jboss.org/pull/982

Waiting to see if the same approach works on here too. Maybe we diverged on some functionality :-(

**Comment by paulrobinson** [comment]
Ok, I see now that https://github.com/redhat-developer/developers.redhat.com/pull/489 is not what you want.

**Comment by eschabell** [comment]
Not working: 

http://www-stg.jboss.org/pr/981/build/2264/products/bpmsuite/overview/

screen shot 2015-10-21 at 10 13 48 am

**Comment by eschabell** [comment]
Is this progressing?

**Comment by LightGuard** [comment]
Traveling today, J1 next week. I'll do my best

On Thursday, October 22, 2015, Eric D. Schabell <notifications@github.com>
wrote:

> Is this progressing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/981#issuecomment-150292326>
> .
>


-- 
Sent from Gmail Mobile

**Comment by eschabell** [comment]
Tested http://it-developers-pr.stage.redhat.com/pr/489/build/1025/products/bpmsuite/buzz/ but:

screen shot 2015-10-23 at 8 58 46 am

**Comment by eschabell** [comment]
Any updates on this?

**Comment by paulrobinson** [comment]
@LightGuard has just got back from J1. He's pretty busy this week, but @Dantheman720 might be able to investigate.

**Comment by Dantheman720** [comment]
I can take a look at this.

**Comment by paulrobinson** [comment]
Dan put in a fix for this: https://github.com/jboss-developer/www.jboss.org/commit/dceaf2a11892de5f262c0eeebd470bff3e5c261a

It seems to be working:  http://www.jboss.org/products/bpmsuite/overview/

@eschabell I'm closing this PR as I think we have it working. Please let us know if you think otherwise.

**Comment by eschabell** [comment]
Yes, fixed now, thanks.

**Pull request closed without merging**
