### PR TITLE
Adding the Enterprise_Java Microsite

### PR DESCRIPTION
**Pull request by myfear**
First round for Enterprise Java Microsite.

### CODE REVIEW

**Comment by myfear** [comment]
@paulrobinson can you look at this please. The Cover image is still not using the one it should be. And I badly need a better example of how to embed videos :) Thanks!

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by myfear** [comment]
Looks good! Let's get this live :)

**Pull request closed without merging**
