### PR TITLE
Updated bpm suite product overveiw page, new vimeo link.

### PR DESCRIPTION
**Pull request by eschabell**
Tried a youtube video link, but that does not work, imported it into vimeo, trying again.

### CODE REVIEW

**Comment by eschabell** [comment]
Perfect, please merge to main site.

**Comment by eschabell** [comment]
Can we add the link used here: https://github.com/redhat-developer/developers.redhat.com/pull/485

intro_video: https://vimeo.com/142883902

That is hosted by jboss developer so good right?

**Comment by paulrobinson** [comment]
I've created https://github.com/jboss-developer/www.jboss.org/pull/978 for the intro video. You can add the other videos to the product album/playlist, as described in the contributing guide.

**Comment by eschabell** [comment]
Thanks, you can close this one then?

**Pull request closed without merging**
