### PR TITLE
DEVELOPER-1227 Update to TicketMonster 2.7.0.Final

### PR DESCRIPTION
**Pull request by VineetReynolds**
Updated TicketMonster submodule commit hash, and link to PDF and items in ToC.

### CODE REVIEW

**Comment by paulrobinson** [comment]
It looks like there's still Asciidoc issues:

https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/www.jboss.org-pull-player-executor/1730/console

Can you take a look?

**Comment by VineetReynolds** [comment]
I wasn't able to reproduce the issue on Mac and Fedora 20. Retrying however with a couple of changes in the asciidoc files, since the stacktrace hinted that the headers were incorrect.

**Comment by VineetReynolds** [comment]
Seems to fail due to Google API client. Retesting

**Comment by VineetReynolds** [comment]
retest this please

**Comment by paulrobinson** [comment]
It's failing now due to an Asciidoc parsing issue. Maybe @LightGuard can give you some debugging tips?

**Comment by VineetReynolds** [comment]
Yeah. I can't seem to figure what file and what header causes this. It still fails in parsing/loading the adoc file headers, but this is not reproducible locally.

**Comment by VineetReynolds** [comment]
Looks like the parsing issue should be fixed now going by the latest build in PR #811

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
The build now seems to fail elsewhere when parsing yaml files. @paulrobinson any ideas if this was fixed elsewhere?

**Comment by LightGuard** [comment]
Please put the Gemfile back to the way it was :)

On Wednesday, March 4, 2015, Vineet Reynolds <notifications@github.com>
wrote:

> The build now seems to fail elsewhere when parsing yaml files.
> @paulrobinson <https://github.com/paulrobinson> any ideas if this was
> fixed elsewhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/801#issuecomment-77156536>
> .
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by VineetReynolds** [comment]
@LightGuard Well the GemFile changes are in PR #811 not in this :|

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
Looks like a problem on the Jenkins slave. Retrying.

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
retest this please

**Comment by VineetReynolds** [comment]
Well, the failure now is a result of https://issues.jboss.org/browse/DEVELOPER-1232

**Comment by VineetReynolds** [comment]
retest this please

**Comment by paulrobinson** [comment]
You also need to update the `https://github.com/jboss-developer/ticket-monster/archive/2.6.0.Final-with-tutorials.zip[DOWNLOAD IT]` bit of ticket-monster.adoc

**Comment by VineetReynolds** [comment]
Good catch. Thanks

**Comment by mareknovotny** [comment]
@paulrobinson, @VineetReynolds guys, could we merge it now, when it passes the CI?

**Pull request merged**
