### PR TITLE
DEVELOPER-1218 - updated WFK developer materials to 2.7.0.GA release

### PR DESCRIPTION
**Pull request by mareknovotny**

### CODE REVIEW

**Comment by paulrobinson** [comment]
There seems to be a problem parsing one or more of the asciidoc files in the new Ticket Monster tag. Unfortunately, the log doesn't say which one :-(

**Comment by mareknovotny** [comment]
@VineetReynolds do you have an idea what is wrong? I haven't tried to generate asciidoc documents, so I am blind for today and my home computer doesn't have the setup for generating them. Could you look at the https://github.com/jboss-developer/ticket-monster/releases/tag/2.7.0.Final-with-tutorials tag with tutorial generation?

**Comment by mareknovotny** [comment]
I tried to generate TiMo Tutorial on my ntb and it fails in PDF generation 

```
 ((2.7.0.Final-with-tutorials)) ./generate-guides.sh 
** Building tutorial
**** Cleaning target/guides
**** Copying shared resources to target/guides/html
**** Processing AdminHTML5.asciidoc > target/guides/html/AdminHTML5.html
**** Processing BusinessLogic.asciidoc > target/guides/html/BusinessLogic.html
**** Processing DashboardHTML5.asciidoc > target/guides/html/DashboardHTML5.html
**** Processing DataPersistence.asciidoc > target/guides/html/DataPersistence.html
**** Processing HybridUI.asciidoc > target/guides/html/HybridUI.html
**** Processing Introduction.asciidoc > target/guides/html/Introduction.html
**** Processing JBossDeployment.asciidoc > target/guides/html/JBossDeployment.html
**** Processing OpenShiftDeployment.asciidoc > target/guides/html/OpenShiftDeployment.html
**** Processing ticket-monster.asciidoc > target/guides/html/ticket-monster.html
**** Processing UserFrontEnd.asciidoc > target/guides/html/UserFrontEnd.html
**** Processing WhatIsTicketMonster.asciidoc > target/guides/html/WhatIsTicketMonster.html
**** Copying shared resources to target/guides/xml
**** Processing ticket-monster.asciidoc > target/guides/xml/ticket-monster.xml
**** Copying shared resources to target/guides/epub
**** Processing ticket-monster.asciidoc > target/guides/epub/ticket-monster.epub
**** Copying shared resources to target/guides/pdf
**** Processing ticket-monster.asciidoc > target/guides/pdf/ticket-monster.pdf
a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty" -s custom-asciidoc-dblatex.sty -P latex.output.revhistory=0  "/home/mnovotny/projects/git/wfk/ticket-monster/tutorial/target/guides/pdf/ticket-monster.xml" returned non-zero exit status 127
```
@paulrobinson could you get the details from CI and check if that is the same?

**Comment by mareknovotny** [comment]
so It seems my previous shown error is related to missing asciidoc dblatex dependency - https://bugzilla.redhat.com/show_bug.cgi?id=953837, so after installing it it throws error code 1 instead of 127.
@paulrobinson do you use this batch script too in CI https://github.com/jboss-developer/ticket-monster/blob/2.7.0.Final-with-tutorials/tutorial/generate-guides.sh

**Comment by VineetReynolds** [comment]
@mareknovotny I have reason to believe that some of the asciidoc files in TicketMonster may have issues. This would not be detected by the asciidoctor executable used by the TiMo scripts, but crops up when the asciidoctor gem is used by the awestruct site.

**Comment by paulrobinson** [comment]
@VineetReynolds you should now have access to the password vault, so you can try building this PR on your own machine.

**Comment by mareknovotny** [comment]
@paulrobinson, @VineetReynolds: Should I remove ticket-monster update for now to process at least other WFK 2.7.0 updates?

**Comment by paulrobinson** [comment]
Yes I think so s they are essentially independent.

**Pull request merged**
