### PR TITLE
DEVELOPER-1348 - Please update the Data Virtualization WebUI

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@LightGuard Do I need to do anything in addition to that curl to clear the cache?  It still seems to be picking up an event that I only had half-way added.  I have no idea why.  It builds locally just fine with the cache cleared.

**Comment by LightGuard** [comment]
It takes some time for the jdg cache to fully clear, maybe that's what
you're seeing.

On Tuesday, June 30, 2015, Dantheman720 <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> Do I need to do anything in
> addition to that curl to clear the cache? It still seems to be picking up
> an event that I only had half-way added. I have no idea why. It builds
> locally just fine with the cache cleared.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/www.jboss.org/pull/922#issuecomment-117433267>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
